name: Bug Report
description: File a bug report
title: "[Bug or Issue]: Keep this summary short and simple, fit for a readable title "
labels: ["bug", "triage"]
assignees:
  - FIRECATinBLACK
  - OneQuish
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Before you get started please search for your problem in the already existing issues to avoid any duplicates!
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: I did this and then the game did this and also that was visible and that other thing wasnt right either and it affected the gameplay in this way
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce?
      description: Also tell us, what did you expect to happen?
      placeholder: 1) start a new game, 2) go to this region 3) etc.. > Result
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.5.1.a (Public Alpha) 
        - 1.5.1.b (Beta Tester)
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: markdown
  attributes:
    value: "Tip: you can find logs in ```C:\Program Files (x86)\Steam\steamapps\common\Rain World``` in the console.log and exception.log files. Please do NOT submit error logs that have been altered by the UwU text mod"
  - type: checkboxes
    id: downpour
    attributes:
      label: Downpour DLC
      description: Did you use the rainworld Downpour DLC and had the "More Slugcats Expansion" on?
      options:
        - label: More Slugcats Expansion was enabled
          required: true
